Common app-wide config (optional)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.profiles.active=dev


#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LibDev;encrypt=false;trustServerCertificate=false
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=dipul.kumar
#spring.datasource.password=Dipul@123
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update


